<?php
	class Paging extends CI_Model{
	
		public function __construct(){
			parent::__construct();
		}
		//Seputar tanah haram
		
		function berita_record_count(){
			return $this->db->count_all('BERITA');
		}
		function berita_fetch($limit, $start){
			$this->db->select('BERITA.ID_BERITA, BERITA.TANGGAL, BERITA.JUDUL, BERITA.ISI_BERITA, BERITA.GAMBAR, BERITA.ID_KATEGORI_USER, KATEGORI_USER.NAMA_KATEGORI_USER');
			$this->db->from('BERITA');
			$this->db->join('KATEGORI_USER','BERITA.ID_KATEGORI_USER = KATEGORI_USER.ID_KATEGORI_USER');
			$this->db->order_by('BERITA.ID_BERITA','DESC');
			$this->db->limit($limit, $start);
			
			$query = $this->db->get();
			
			if ($query->num_rows() > 0) {
				foreach ($query->result() as $row) {
					$data[] = $row;
				}
				return $data;
			}
			//return false;
		}
		function gallery_record_count(){
			return $this->db->count_all('GALLERY');
		}
		function gallery_fetch($limit, $start){
		   $this->db->select('ID_GALLERY, NAMA_GALLERY, ID_KATEGORI_USER, ID_PELATIHAN');
		   $this->db->from('GALLERY');
		   $this->db->order_by('ID_GALLERY','DESC');
		   $this->db->limit($limit, $start);
		   
		   $query = $this->db->get();
			if($query->num_rows() > 0){
				foreach($query->result() as $data){
					$hasil[] = $data;
				}
				return $hasil;
			}
		}
		function komentar_record_count(){
			return $this->db->count_all('KOMENTAR');
		}
		function komentar_fetch($limit, $start){
			$this->db->select('KOMENTAR.ID_KOMENTAR, KOMENTAR.NAMA_KOMENTAR, KOMENTAR.EMAIL_KOMENTAR, KOMENTAR.ID_BERITA, KOMENTAR.ISI_KOMENTAR, KOMENTAR.STATUS, KOMENTAR.TANGGAL_KOMENTAR, BERITA.JUDUL');
			$this->db->from('KOMENTAR');
			$this->db->join('BERITA','KOMENTAR.ID_BERITA = BERITA.ID_BERITA');
			$this->db->order_by('KOMENTAR.ID_KOMENTAR','DESC');
		    $this->db->limit($limit, $start);
			$query = $this->db->get();
			
			if ($query->num_rows() > 0) {
				foreach ($query->result() as $row) {
					$data[] = $row;
				}
				return $data;
			}
			return false;
		}
		function instruktur_recourd_count(){
			$vars = $this->db->query("SELECT TBL_USER.ID_USER, TBL_USER.USERNAME, TBL_USER.PASSWORD, TBL_USER.ID_KATEGORI_USER, TBL_USER.NAMA_LENGKAP, TBL_USER.TEMPAT_LAHIR, TBL_USER.TANGGAL_LAHIR, TBL_USER.ALAMAT, TBL_USER.NOTEL, TBL_USER.AGAMA, TBL_USER.EMAIL, TBL_USER.STATUS_PEKERJAAN, TBL_USER.VALIDASI, TBL_USER.FOTO, TBL_USER.JENIS_KELAMIN, TBL_USER.EDUKASI, TBL_USER.NMOR_IDENTITAS,REGISTRASI_MENGAJAR.ID_REGISTRASI_MENGAJAR, REGISTRASI_MENGAJAR.ID_USER, REGISTRASI_MENGAJAR.HARI_MENGAJAR, REGISTRASI_MENGAJAR.JAM_MENGAJAR, REGISTRASI_MENGAJAR.ID_PELATIHAN FROM TBL_USER, REGISTRASI_MENGAJAR WHERE REGISTRASI_MENGAJAR.ROWID IN (SELECT MAX(ROWID) FROM REGISTRASI_MENGAJAR GROUP BY REGISTRASI_MENGAJAR.ID_PELATIHAN, REGISTRASI_MENGAJAR.ID_USER) AND TBL_USER.VALIDASI = 1 AND REGISTRASI_MENGAJAR.VALIDASI = 1 AND STATUS_MENGAJAR = 1 AND TBL_USER.ID_KATEGORI_USER = 2 AND TBL_USER.ID_USER = REGISTRASI_MENGAJAR.ID_USER ORDER BY REGISTRASI_MENGAJAR.ID_REGISTRASI_MENGAJAR DESC");
			
			return $vars->num_rows();
		}
		function baca_instruktur($limit, $start){
			/*$query = $this->db->query("SELECT TBL_USER.ID_USER, TBL_USER.USERNAME, TBL_USER.PASSWORD, TBL_USER.ID_KATEGORI_USER, TBL_USER.NAMA_LENGKAP, TBL_USER.TEMPAT_LAHIR, TBL_USER.TANGGAL_LAHIR, TBL_USER.ALAMAT, TBL_USER.NOTEL, TBL_USER.AGAMA, TBL_USER.EMAIL, TBL_USER.STATUS_PEKERJAAN, TBL_USER.VALIDASI, TBL_USER.FOTO, TBL_USER.JENIS_KELAMIN, TBL_USER.EDUKASI, TBL_USER.NMOR_IDENTITAS,REGISTRASI_MENGAJAR.ID_REGISTRASI_MENGAJAR, REGISTRASI_MENGAJAR.ID_USER, REGISTRASI_MENGAJAR.HARI_MENGAJAR, REGISTRASI_MENGAJAR.JAM_MENGAJAR, REGISTRASI_MENGAJAR.ID_PELATIHAN FROM TBL_USER, REGISTRASI_MENGAJAR WHERE REGISTRASI_MENGAJAR.ROWID IN (SELECT MAX(ROWID) FROM REGISTRASI_MENGAJAR GROUP BY REGISTRASI_MENGAJAR.ID_PELATIHAN, REGISTRASI_MENGAJAR.ID_USER) AND TBL_USER.VALIDASI = 1 AND TBL_USER.ID_KATEGORI_USER = 2 AND TBL_USER.ID_USER = REGISTRASI_MENGAJAR.ID_USER AND rownum <= $limit AND rownum >=$start ORDER BY REGISTRASI_MENGAJAR.ID_REGISTRASI_MENGAJAR DESC"); 
		
		/*$this->db->select('TBL_USER.ID_USER, TBL_USER.USERNAME, TBL_USER.PASSWORD, TBL_USER.ID_KATEGORI_USER, TBL_USER.NAMA_LENGKAP, TBL_USER.TEMPAT_LAHIR, TBL_USER.TANGGAL_LAHIR, TBL_USER.ALAMAT, TBL_USER.NOTEL, TBL_USER.AGAMA, TBL_USER.EMAIL, TBL_USER.STATUS_PEKERJAAN, TBL_USER.VALIDASI, TBL_USER.FOTO, TBL_USER.JENIS_KELAMIN, TBL_USER.EDUKASI, TBL_USER.NMOR_IDENTITAS,REGISTRASI_MENGAJAR.ID_REGISTRASI_MENGAJAR, REGISTRASI_MENGAJAR.ID_USER, REGISTRASI_MENGAJAR.HARI_MENGAJAR, REGISTRASI_MENGAJAR.JAM_MENGAJAR, REGISTRASI_MENGAJAR.ID_PELATIHAN');
		$this->db->from('TBL_USER');
		$this->db->join('REGISTRASI_MENGAJAR','TBL_USER.ID_USER = REGISTRASI_MENGAJAR.ID_USER');
		$this->db->where('TBL_USER.VALIDASI = 1');
		$this->db->where('TBL_USER.ID_KATEGORI_USER = 2');
		$this->db->where('REGISTRASI_MENGAJAR.ROWID IN (SELECT MAX(ROWID) FROM REGISTRASI_MENGAJAR GROUP BY REGISTRASI_MENGAJAR.ID_PELATIHAN, REGISTRASI_MENGAJAR.ID_USER)');
		$this->db->order_by('REGISTRASI_MENGAJAR.ID_REGISTRASI_MENGAJAR','DESC');
		$this->db->limit($limit, $start);
		$query = $this->db->get();*/
		
		$query = $this->db->query("SELECT * FROM 
			(
				SELECT U.ID_USER AS UI, U.USERNAME, U.PASSWORD, U.ID_KATEGORI_USER, U.NAMA_LENGKAP, U.TEMPAT_LAHIR, U.TANGGAL_LAHIR, U.ALAMAT, U.NOTEL, U.AGAMA, U.EMAIL, U.STATUS_PEKERJAAN, U.VALIDASI, U.FOTO, U.JENIS_KELAMIN, U.EDUKASI, U.NMOR_IDENTITAS,R.ID_REGISTRASI_MENGAJAR, R.ID_USER AS IU, R.HARI_MENGAJAR, R.JAM_MENGAJAR, R.ID_PELATIHAN, 
				ROWNUM AS RN
				FROM TBL_USER U, REGISTRASI_MENGAJAR R 
				WHERE R.ROWID IN (SELECT MAX(ROWID) FROM REGISTRASI_MENGAJAR RR GROUP BY RR.ID_PELATIHAN, RR.ID_USER, RR.TANGGAL_MENGAJAR) AND U.VALIDASI = 1 AND R.VALIDASI = 1 AND STATUS_MENGAJAR = 1 AND U.ID_KATEGORI_USER = 2 AND U.ID_USER = R.ID_USER 
				ORDER BY R.ID_REGISTRASI_MENGAJAR DESC
			) sub
			WHERE sub.RN <= $limit AND sub.RN >=$start");
			
			if ($query->num_rows() > 0) {
				foreach ($query->result() as $row) {
					$data[] = $row;
				}
				return $data;
			}
			return false;
		}
		
	}
?>